server:
  port: 8080
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
   password: root
   username: root
   driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: daidai

mybatis:
  map-underscore-to-camel-case: true
  type-aliases-package: com.qf.beans
  mapper-locations: classpath:mappers/*Mapper.xml

